### PR TITLE
calculate value with token precision. Fix #574

### LINKED ISSUE #574: Custom Asset amount shows incorrect in wallet dashboard
This is a custom asset developed by RSK developer. 

Network: Testnet
Symbol: Sol
Precision: 2
Token Contract: https://explorer.testnet.rsk.co/address/0x42dde210f3e7d71d3df9ad96e05cbe0045b7cccd
Token Faucet: https://token.solange.dev/

Here I send a transaction of 1000 Sol.
https://explorer.testnet.rsk.co/tx/0x9132052af00ebbf5b8d347d4ece6e59f02d256314113247cddcbae5d64ef6288

Push Notification shows correct amount: 1000
image

But transaction and wallet dashboard shows balance 0. **Is it because the precision in wallet dashboard always 18?**
image
image
image

### PR DESCRIPTION
**Pull request by AmazingBeerBelly**

### CODE REVIEW

File: src/common/common.js [hunk 1]
```diff
@@ -57,16 +57,26 @@ const common = {
     const result = new BigNumber(satoshi).div('1e8');
     return result;
   },
-  rskCoinToWeiHex(amount) {
-    const result = `0x${this.rskCoinToWei(amount).decimalPlaces(0).toString(16)}`;
+  rskCoinToWeiHex(amount, precision) {
```
Comment (chrisli30) [inline src/common/common.js:60]: Do we really need 2 functions for decimal numbers and hex numbers?

The best ways should be using rskCoinToWei() to return a big number, then you can use rsk3.utils functions to get hex or decimal number.

File: src/common/common.js [hunk 2]
```diff
@@ -57,16 +57,26 @@ const common = {
...
+    const result = `0x${this.rskCoinToWei(amount, precision).decimalPlaces(0).toString(16)}`;
     return result;
   },
-  rskCoinToWei(amount) {
-    const result = new BigNumber(amount).times('1e18');
+  rskCoinToWei(amount, precision = null) {
```
Comment (chrisli30) [inline src/common/common.js:64]: precision has to be an integer, maybe add protection using _.floor(precision)

Add comments, what are the example values of amount and precision?

File: src/common/common.js [hunk 3]
```diff
@@ -84,11 +94,11 @@ const common = {
    * @param {*} symbol
    * @param {*} unitNumber
    */
-  convertUnitToCoinAmount(symbol, unitNumber) {
+  convertUnitToCoinAmount(symbol, unitNumber, precision = null) {
```
Comment (chrisli30) [inline src/common/common.js:97]: 你这里设计的我觉得考虑的不周到，precision默认与其是null，不如是默认的18位, 如果忘了传，这里设置成null，代码里还是要设置成18位，不如这里默认值是18，你里面那些函数就不用加if null check了

**Review by chrisli30 — CHANGES_REQUESTED** [review]

**Review by imstar15 — APPROVED** [review]

**Review by imstar15 — CHANGES_REQUESTED** [review]
rskCoinToWeiHex， weiToCoin， convertUnitToCoinAmount， 这几个函数都在代码里全局查找下，看看有没有漏了没改的，需要保证都传了precision参数进去。

cointype.js里每一个rsk token都写上precision属性
在rbtccoin的构造函数里需要把这个属性赋值到实例里。

**Review by chrisli30 — APPROVED** [review]
Yeah, looks good to me.

**Review by imstar15 — APPROVED** [review]

File: src/common/common.js [hunk 4]
```diff
@@ -57,17 +57,32 @@ const common = {
...
-    return result;
+  /**
+   * Transform coin value to wei unit
+   * Example: RIF, precision = 18, 0.001 RIF = 1e15 (wei) RIF
+   * Example: SOL, precision = 2, 1 SOL = 100 (wei) SOL
+   * @param {*} amount
+   * @param {*} precision
+   */
+  rskCoinToWei(amount, precision = 18) {
+    const precisionInteger = _.floor(Number(precision));
```
Comment (bguiz) [inline src/common/common.js:72]: instead of floor, which masks input errors, this should reject non integer values explicitly, throwing an error. I suggest that you use this to test: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

additionally negative values for precision are not legal according to the EIP (unsigned integer in Solidity), so you need to also add a check that rejects values less than zero.

File: src/common/common.js [hunk 5]
```diff
@@ -57,17 +57,32 @@ const common = {
...
+
+  /**
+   * Transform wei unit value to coin value
+   * Example: RIF, precision = 18, 1e15 (wei) RIF = 0.001 RIF
+   * Example: SOL, precision = 2, 100 (wei) SOL = 1 SOL
+   * @param {*} wei
+   * @param {*} precision
+   */
+  weiToCoin(wei, precision = 18) {
+    const precisionInteger = _.floor(Number(precision));
```
Comment (bguiz) [inline src/common/common.js:84]: same comment as above about rejecting non-integer values and negative values as inputs.

File: src/pages/wallet/add.custom.token.confirm.js [hunk 6]
```diff
@@ -158,7 +158,7 @@ class AddCustomToken extends Component {
         }
         const result = await CancelablePromiseUtil.makeCancelable(parseHelper.getUserTokenBalance(type, chain, contractAddress, address), this);
         console.log('UserTokenBalance: ', result);
-        this.setState({ balance: common.weiToCoin(result.balance) });
+        this.setState({ balance: common.weiToCoin(result.balance, this.decimals) });
```
Comment (bguiz) [inline src/pages/wallet/add.custom.token.confirm.js:161]: naming inconsistency - using `decimals` here but `precision` elsewhere. let's change all instances to use the same variable name.
