### PR TITLE
Fix incorrect number of wallets. fix #31

### LINKED ISSUE #31: The number of wallets in a key not always shows the correct number
The number of wallets in a key not always shows the correct number when you make changes to the assets you manage in the key (I don't have the detailed steps to reproduce it but it kind of fails when you remove all assets and go to the Me section)

### PR DESCRIPTION
**Pull request by imstar15**

### CODE REVIEW

File: src/pages/mine/index.js [hunk 1]
```diff
@@ -153,8 +153,7 @@ class MineIndex extends Component {
             <View style={styles.right}>
               <Text>{item.name}</Text>
               <Text style={styles.keyWallets}>
-                {`${item.walletCount} `}
-                <Loc text="page.mine.index.wallets" />
+                <Loc text="page.mine.index.wallets" interpolates={{ count: item.walletCount }} />
```
Comment (chrisli30) [inline src/pages/mine/index.js:156]: 没看懂这个 zero, one, other是在哪里传进去的。

Comment (imstar15) [reply src/pages/mine/index.js:156]: This is the rule of i18n.
http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html.

for example:

config: 
```
en:
  inbox:
    counting:
      one: You have 1 new message
      other: You have {{count}} new messages
      zero: You have no messages
```

code:
`I18n.t("inbox.counting", {count: 10});  // You have 10 messages `

Comment (chrisli30) [reply src/pages/mine/index.js:156]: 哦 原来可以这样用
