### PR TITLE
Fix pt-BR. fix #335

### LINKED ISSUE #335: Bug: If I install rwallet, the app start with Portuguese language and not Portuguese Brazilian as it should be
If I install rwallet, the app start with Portuguese language and not Portuguese Brazilian as it should be.

Obs. Android is configured with Portuguese Brazilian language.

### PR DESCRIPTION
**Pull request by imstar15**

### CODE REVIEW

File: src/common/common.js [hunk 1]
```diff
@@ -399,12 +399,8 @@ const common = {
...
 
   setMomentLocale(locale) {
-    let newLocale = locale;
-    if (locale === 'zh') {
-      newLocale = 'zh-cn';
-    } else if (locale === 'ptBR') {
-      newLocale = 'pt-br';
-    }
+    const newLocale = locale === 'zh' ? 'zh-cn' : locale;
+    // pt-BR will be normalize to pt-br
```
Comment (chrisli30) [inline src/common/common.js:403]: okay 看懂了  comments are good
